server:
  port: 0

spring:
  application:
    name: cloud-ex-second

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
