spring:
 datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    # password: '{cipher}1e0d061142e9b5804af4456d96fb51ed8eaea5547edecffa4387be6a1ef152a0' <<<< 대칭키 사용
    password: '{cipher}AQANBj4idH3iAOxleUhAeIPmsKYx22Bn+OFN42dXQHsPJV4tJ/nwbueZyJlcEIdo1PKUUkHjnZmVEHqL1s2zij96X/y3K11R75WpTJsQmMYlVd1OobAQnMIezv3msnXed1Wd6o4joEI0MQRs7CG/ZlD+2fm2uxAoqUnpAPRVW6Gvy6D5vqxKhBIumSwf4CK9Ym9c2aHJm1HxvLvVjbkrccLfYVcZae29V4IAEFIdlp4hgL00ikcHKBZLfYiuof5KSPPHzKQ3ovaZpQ0iRYCFX3/dpJpeQ3HenJid8NJOyxKb+LgTYQeL7tcxxtPAZoiTwuySq5bHocSLqDlLUlNO4dfbWKGXLTfoO0MHfoEcsXHKLM0cTKNI/5Bs7i337jlvUxw='
    # {cipher}는 암호화 되었다고 알려주는 힌트
    driver-class-name: org.h2.Driver

token:
  expiration_time: 86400000
  secret: jwt_token_secret_key_test_dev_#9

gateway:
  ip: 192.168.1.210