spring:
 datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: jangto
    # password: '{cipher}1e0d061142e9b5804af4456d96fb51ed8eaea5547edecffa4387be6a1ef152a0' <<<< 대칭키 사용
    password: '{cipher}AQC2bpMutE5M35923lt0Mq+lF1NPk7cSz1oTPflilQfXyShzxArYVUGcaCrRnp5d97WLyhp4yN2Sm+L0G6caP5OloLVSIEqLKyT9Ih1siw5u3rJNsRpyhNSlx7kq2RI/p/EgwTREMf/4wKHH1nHnX3q+hU6BUWtV7IFSX7frTPrulKKcMuZiOgeyg8nPdjQhLIL5pCUuQYk8z7YAUl8b2a2plvfcjiz/t036oLEqNDuGIHUyoAJhsnSqFjQjSIVSWIbiUh7b1iHu/whs3CxigCNw55bLxtbXyZa7ej8pFfZCqFo6fsJ04HtQYNVtjRvmsnnOrDFFYPbnV/SMxuDaC6NZ1Bf3lyH4vu1fA96jZvykJVbOHW7sd/xX03tuneQtm50='
    # {cipher}는 암호화 되었다고 알려주는 힌트
    driver-class-name: com.mysql.jdbc.Driver

# token:
#   expiration_time: 86400000
#   secret: '{cipher}AQBeDyb71ZVQhIXQPd3BRHl5i2oO6kRZ3KTLHFIapSI3de0W3HI30DQ+uWcgLDo7XMfMrKEU1fVswX7GYRk4U7CjcbgJ92sxMD5+Ltsa6y7EMD++bm0669NPI94s253HSc8JyOrP1W4jEnjlvgUNVP0tQ7AbasOfUXB9zl7sOLjf3EO894sQ3koa71T+T3fOF0siH7xMFqL3fnXtlhq9PA1Z7H+OAJ6ef19X2Hl1nQKnMdO5jEHj/333TAgFv1xuwNiItsaU/q7Nr2v+JTxROVAciIC1iJvlzpLFvlzlqTXUiORfTyD4ErKlayLEH0/A73OSQAzCV2FLMRSONKevoSF61jBbQCT7igWB2K00BVMnlqQtLReIq4CxfAjtHx7tbL2dzqnCjea2NmzGgbg1v5+wD0XVyr0OHbvemG1TjX9g/Q=='

gateway:
  ip: 192.168.1.210


order_service:
  # url: http://127.0.0.1:8000/order-service/%s/orders <<< url 값이 바뀌면 모두 찾아가야 하지만
  url: http://CLOUD-ORDER-SERVICE/%s/orders # <<< 이렇게 eureka 서버에 등록된 걸 적어줘도 된다. 단, 해당 properties를 사용하는 곳에서 @LoadBalanced를 @Bean 등록시 해줘야한다.
  exception:
    orders_is_empty: Users's orders is Empty.