spring:
 datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

token:
  expiration_time: 86400000
  secret: jwt_token_secret_key_test_dev_#9

gateway:
  ip: 192.168.1.210