server:
  port: 8888

spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        git:
          uri: file:///C:/spring-cloud-study # .git이 있는 루트 파일
          searchPaths: git-local-repo # 하위 디렉토리의 경우 searchPaths를 통해 지정해줘야한다.